### PR TITLE
Fix diffuse btdf aov components

### LINKED ISSUE #2372: Review albedo initialization in BSDFs
It seems that some BSDFs don't return the correct albedo, for instance the Diffuse BTDF (`diffusebtdf.cpp`) returns `values->m_transmittance` while it should probably return `sample.m_value.m_diffuse`:

    // Compute the BRDF value.
    sample.m_value.m_diffuse = values->m_transmittance;
    sample.m_value.m_diffuse *= values->m_transmittance_multiplier * RcpPi<float>();
    sample.m_value.m_beauty = sample.m_value.m_diffuse;

    // ...

    sample.m_aov_components.m_albedo = values->m_transmittance;

Same problem with the Diffuse BRDF, and possibly others.

### PR DESCRIPTION
**Pull request by mandeep**
fixes #2372 

Not much discussion happened on the issue tracker for this issue so I'm just going to submit this and we can discuss further if needed.

### CODE REVIEW

File: src/appleseed/renderer/modeling/bsdf/diffusebtdf.cpp [hunk 1]
```diff
@@ -139,7 +139,7 @@ namespace
                 sample.m_value.m_diffuse = values->m_transmittance;
                 sample.m_value.m_diffuse *= values->m_transmittance_multiplier * RcpPi<float>();
                 sample.m_value.m_beauty = sample.m_value.m_diffuse;
-                sample.m_aov_components.m_albedo = values->m_transmittance;
+                sample.m_aov_components.m_albedo = sample.m_value.m_diffuse;
```
Comment (est77) [inline src/appleseed/renderer/modeling/bsdf/diffusebtdf.cpp]: What we really want is values->m_transmittance * values->m_transmittance_multiplier, 
without the RcpPi<float>() factor.

What you can do is compute the albedo first and then:

diffuse = albedo;
diffuse *= RcpPi<float>();

Comment (mandeep) [reply src/appleseed/renderer/modeling/bsdf/diffusebtdf.cpp]: I submitted a new change, but we want albedo = diffuse right?
