### PR TITLE
Use regular AOVs to export diagnostic AOVs

### LINKED ISSUE #2068: Fix bad pixels when crop window is overlapping tiles
When the crop window is overlapping on tiles, AOVs (maybe diagnostics only) have incorrect pixels.

But the final image is correct.

Also happens with the uniform pixel/tile renderer.

### PR DESCRIPTION
**Pull request by oktomus**
- [x] Copy diagnostic AOVs into real AOVs
- [x] Remove `enable_diagnostics` option and check whether the use has set the wanted AOV
- [x] Don't create extra aovs but directly write into regular aovs from the pixel renderers
- [x] ? Write directly in the AOV
- [x] Post process in the AOV and not in the renderer
- [x] ? Use write() to detect invalid samples
- Check in both regular and internal aovs instead of `aov_images` -> **not required**

fix #2068

### CODE REVIEW

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 1]
```diff
@@ -0,0 +1,339 @@
...
+        void on_tile_end(
+            const Frame&                frame,
+            const size_t                tile_x,
+            const size_t                tile_y)
+        {
+            for (size_t i = 0, e = frame.aov_images().size(); i < e; ++i)
+            {
+                const string aov_name = frame.aov_images().get_name(i);
+
+                if (aov_name == m_diagnostic_name)
```
Comment (est77) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Do the linear search only the first time it is needed. The image does not change while the AOVAccumulator is alive and accumulators are not shared between threads.

const Image* m_image = nullptr;
if (!m_image) { do the search here... }

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 2]
```diff
@@ -0,0 +1,339 @@
...
+        }
+
+        void release() override
+        {
+            delete this;
+        }
+
+        size_t get_channel_count() const override
+        {
+            return 4;
```
Comment (est77) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Do we need 4 channels?
Some of the previous AOVs use only one (you can save them using 1 channel called "Y") and the pixel variation is RGB (no need for A).

Comment (oktomus) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Yes I will improve that when implementing per-aov post process

File: src/appleseed/renderer/kernel/rendering/final/uniformpixelrenderer.cpp [hunk 3]
```diff
@@ -187,7 +185,10 @@ namespace
                             static_cast<float>(pt.y + s.y),
                             shading_result);
                     }
-                    else signal_invalid_sample();
+                    else
+                    {
+                        signal_invalid_sample();
```
Comment (est77) [inline src/appleseed/renderer/kernel/rendering/final/uniformpixelrenderer.cpp]: Remove the braces, leave the code as it was before.
Do the same in the other signal_invalid_sample() call a few lines after.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 4]
```diff
@@ -0,0 +1,501 @@
...
+namespace renderer
+{
+
+namespace
+{
+    //
+    // Diagnostic AOV accumulator.
+    //
+
+    class DiagnosticAOVAccumulator
```
Comment (est77) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: We are not using this class, no?

File: src/appleseed/renderer/modeling/aov/pixeltimeaov.cpp [hunk 5]
```diff
@@ -218,16 +218,14 @@ namespace
             m_image->clear(Color<float, 1>(0.0f));
         }
 
-        void post_process_image() override
+        void post_process_image(const AABB2u& bbox) override
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/pixeltimeaov.cpp]: You must inclde `foundation/math/aabb.h` in all files that now require it.

File: src/appleseed/renderer/modeling/aov/aov.h [hunk 6]
```diff
@@ -90,7 +91,7 @@ class APPLESEED_DLLSYMBOL AOV
     virtual void clear_image();
 
     // Apply any post processing needed to the AOV image.
-    virtual void post_process_image();
+    virtual void post_process_image(const foundation::AABB2u& bbox);
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/aov.h]: I believe `bbox` should be called `crop_window` for clarity.

File: src/appleseed/renderer/kernel/rendering/pixelrendererbase.h [hunk 7]
```diff
@@ -97,33 +96,8 @@ class PixelRendererBase
...
-//
-// Pixel renderer base factory.
-//
-
-class PixelRendererBaseFactory
-  : public IPixelRendererFactory
-{
-  public:
-    static foundation::Dictionary get_params_metadata();
+    size_t m_invalid_pixel_count;
```
Comment (dictoon) [inline src/appleseed/renderer/kernel/rendering/pixelrendererbase.h]: Make sure to remove header files that are no longer required.

File: src/appleseed/renderer/kernel/rendering/final/uniformpixelrenderer.cpp [hunk 8]
```diff
@@ -79,7 +79,7 @@ namespace
             ISampleRendererFactory*     factory,
             const ParamArray&           params,
             const size_t                thread_index)
-          : PixelRendererBase(frame, thread_index, params)
+          : PixelRendererBase()
```
Comment (dictoon) [inline src/appleseed/renderer/kernel/rendering/final/uniformpixelrenderer.cpp]: You no longer need to explicitly invoke the constructor here.

**Comment by oktomus** [comment]
@dictoon I will address your review in the adaptive PR :)

File: src/appleseed/renderer/kernel/rendering/final/adaptivepixelrenderer.cpp [hunk 9]
```diff
@@ -293,28 +280,29 @@ namespace
...
-                            static_cast<float>(m_params.m_min_samples),
-                            static_cast<float>(m_params.m_max_samples),
-                            0.0f, 1.0f);
-
-                m_diagnostics->set_pixel(pt.x, pt.y, values);
+                Color3f value(0.0f, 0.0f, 0.0f);
+
+                if (m_sample_aov_tile)
+                {
+                    value[0] = trackers[0].get_size();
```
Comment (dictoon) [inline src/appleseed/renderer/kernel/rendering/final/adaptivepixelrenderer.cpp]: You need a `static_cast<>` here as in general this will loose precision.

File: src/appleseed/renderer/kernel/rendering/generic/generictilerenderer.cpp [hunk 10]
```diff
@@ -157,16 +157,21 @@ namespace
...
-
             // Inform the AOV accumulators that we are about to render a tile.
             m_aov_accumulators.on_tile_begin(
                 frame,
                 tile_x,
                 tile_y,
                 m_pixel_renderer->get_max_samples_per_pixel());
 
+            // Inform the pixel renderer that we are about to render a tile.
+            m_pixel_renderer->on_tile_begin(
```
Comment (dictoon) [inline src/appleseed/renderer/kernel/rendering/generic/generictilerenderer.cpp]: Why did you move this?

File: src/appleseed/renderer/kernel/rendering/pixelrendererbase.cpp [hunk 11]
```diff
@@ -154,21 +92,20 @@ void PixelRendererBase::on_pixel_end(
     const AABB2i&               tile_bbox,
     AOVAccumulatorContainer&    aov_accumulators)
 {
-    aov_accumulators.on_pixel_end(pi);
+    static const size_t MaxWarningsPerThread = 5;
 
-    // todo: mark pixel as faulty in the diagnostic map.
```
Comment (dictoon) [inline src/appleseed/renderer/kernel/rendering/pixelrendererbase.cpp]: If I understand correctly this todo is done because we now have a dedicated Invalid Samples AOV?

File: src/appleseed/renderer/modeling/aov/aovfactoryregistrar.cpp [hunk 12]
```diff
@@ -89,8 +90,11 @@ void AOVFactoryRegistrar::reinitialize(const SearchPaths& search_paths)
     register_factory(auto_release_ptr<FactoryType>(new GlossyAOVFactory()));
     register_factory(auto_release_ptr<FactoryType>(new IndirectDiffuseAOVFactory()));
     register_factory(auto_release_ptr<FactoryType>(new IndirectGlossyAOVFactory()));
+    register_factory(auto_release_ptr<FactoryType>(new InvalidSampleAOVFactory()));
     register_factory(auto_release_ptr<FactoryType>(new NormalAOVFactory()));
+    register_factory(auto_release_ptr<FactoryType>(new PixelSampleAOVFactory()));
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/aovfactoryregistrar.cpp]: I feel that this AOV name is ambiguous, I would suggest `PixelSampleCountAOV[Factory]`.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 13]
```diff
@@ -0,0 +1,501 @@
...
+    {
+      public:
+        DiagnosticAOVAccumulator()
+        {
+        }
+    };
+
+    //
+    // Invalid Sample AOV accumulator.
+    //
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Remove this line.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 14]
```diff
@@ -0,0 +1,501 @@
...
+
+    class DiagnosticAOVAccumulator
+      : public AOVAccumulator
+    {
+      public:
+        DiagnosticAOVAccumulator()
+        {
+        }
+    };
+
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Always precede block comments by two blank lines?

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 15]
```diff
@@ -0,0 +1,501 @@
...
+    const uint8 NoState = 0;
+    const uint8 InvalidSample = 1;
+    const uint8 CorrectSample = 2;
+
+    class InvalidSampleAOVAccumulator
+      : public AOVAccumulator
+    {
+      public:
+        explicit InvalidSampleAOVAccumulator(
+            Image& image)
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Move argument to precedent line, there's no line length problem here.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 16]
```diff
@@ -0,0 +1,501 @@
...
+          : m_image(image)
+          , m_invalid_sample_count(0)
+        {
+        }
+
+        void on_tile_begin(
+                const Frame&                frame,
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Fix indentation.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 17]
```diff
@@ -0,0 +1,501 @@
...
+            const CanvasProperties& props = frame.image().properties();
+
+            m_tile_origin_x = static_cast<int>(tile_x * props.m_tile_width);
+            m_tile_origin_y = static_cast<int>(tile_y * props.m_tile_height);
+            m_tile_end_x = static_cast<int>(m_tile_origin_x + m_invalid_sample_tile->get_width() - 1);
+            m_tile_end_y = static_cast<int>(m_tile_origin_y + m_invalid_sample_tile->get_height() - 1);
+        }
+
+        void on_tile_end(
+                const Frame&                frame,
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Fix indentation.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 18]
```diff
@@ -0,0 +1,501 @@
...
+        }
+
+        void on_pixel_begin(const Vector2i& pi) override
+        {
+            m_invalid_sample_count = 0;
+        }
+
+        void on_pixel_end(const Vector2i& pi) override
+        {
+            // Store a hint corresping to the sample state in the tile.
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Fix typo

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 19]
```diff
@@ -0,0 +1,501 @@
...
+
+            m_invalid_sample_tile.reset(
+                new Tile(tile.get_width(), tile.get_height(), 1, PixelFormatUInt8));
+            m_invalid_sample_tile->clear(Color<uint8, 1>(0));
+
+            const CanvasProperties& props = frame.image().properties();
+
+            m_tile_origin_x = static_cast<int>(tile_x * props.m_tile_width);
+            m_tile_origin_y = static_cast<int>(tile_y * props.m_tile_height);
+            m_tile_end_x = static_cast<int>(m_tile_origin_x + m_invalid_sample_tile->get_width() - 1);
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Traditionally "end" indices are exclusive, i.e. you don't subtract 1 here, and you change <= to < when checking if pixels fall inside the tile. Simpler math and increased consistency.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 20]
```diff
@@ -0,0 +1,501 @@
...
+    };
+
+    //
+    // Invalid Sample AOV accumulator.
+    //
+    //
+
+    const uint8 NoState = 0;
+    const uint8 InvalidSample = 1;
+    const uint8 CorrectSample = 2;
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: `CorrectSample` -> `ValidSample` (because "valid" is the opposite of "invalid", while "correct" is the opposite of "incorrect").

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 21]
```diff
@@ -0,0 +1,501 @@
...
+
+    //
+    // Diagnostic AOV.
+    //
+
+    class DiagnosticAOV
+      : public AOV
+    {
+      public:
+        explicit DiagnosticAOV(const char* name, const ParamArray& params)
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Remove `explicit`.

Comment (dictoon) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Why is this AOV named while the others aren't?

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 22]
```diff
@@ -0,0 +1,501 @@
...
+        }
+
+        void post_process_image(const AABB2u& bbox) override
+        {
+            static const Color3f Blue(0.0f, 0.0f, 1.0f);
+            static const Color3f Red(1.0f, 0.0f, 0.0f);
+
+            Color3f color;
+
+            for (size_t j = bbox.min.y; j <= bbox.max.y; ++j)
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: It would be more logical to use x and y to iterate.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp [hunk 23]
```diff
@@ -0,0 +1,501 @@
...
+{
+    return Invalid_Sample_Model;
+}
+
+Dictionary InvalidSampleAOVFactory::get_model_metadata() const
+{
+    return
+        Dictionary()
+            .insert("name", Invalid_Sample_Model)
+            .insert("label", "Invalid Sample");
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: "Invalid Samples".

The AOV needs to be renamed too.

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp (hunk 21 above)
Comment (oktomus) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Something I forgot to remove.

File: src/appleseed/renderer/kernel/rendering/generic/generictilerenderer.cpp (hunk 10 above)
Comment (oktomus) [reply src/appleseed/renderer/kernel/rendering/generic/generictilerenderer.cpp]: not required anymore.

File: src/appleseed/renderer/kernel/rendering/pixelrendererbase.cpp (hunk 11 above)
Comment (oktomus) [reply src/appleseed/renderer/kernel/rendering/pixelrendererbase.cpp]: yes

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp (hunk 13 above)
Comment (oktomus) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: You want me to remove the whole block ?

File: src/appleseed/renderer/modeling/aov/diagnosticaov.cpp (hunk 21 above)
Comment (oktomus) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Because other AOVs inherit from this one.

Comment (oktomus) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Why removing explicit ?

Comment (dictoon) [reply src/appleseed/renderer/modeling/aov/diagnosticaov.cpp]: Because it's not useful for constructors with more than one argument... Or at least that was true until C++11: https://stackoverflow.com/a/39122237/393756

It seems that it makes sense starting with C++11 to mark all constructors as explicit... Today I learn!

You can leave `explicit` then. If you already remove it then no big deal, it's fine too.
