### PR TITLE
PNG writing fixes

### LINKED ISSUE #1601: Crash when saving render as PNG from appleseed.studio
image

### PR DESCRIPTION
**Pull request by est77**
Fix #1601 and another bug introduced in the color management PR.

### CODE REVIEW

File: src/appleseed/foundation/image/color.h [hunk 1]
```diff
@@ -1082,6 +1086,27 @@ inline const T& Color<T, 4>::operator[](const size_t i) const
     return (&r)[i];
 }
 
+template <typename T>
+void Color<T, 4>::premultiply()
```
Comment (dictoon) [inline src/appleseed/foundation/image/color.h]: Mark inline maybe?

File: src/appleseed/foundation/image/color.h [hunk 2]
```diff
@@ -1082,6 +1086,27 @@ inline const T& Color<T, 4>::operator[](const size_t i) const
...
+{
+    r *= a;
+    g *= a;
+    b *= a;
+}
+
+template <typename T>
+void Color<T, 4>::unpremultiply()
```
Comment (dictoon) [inline src/appleseed/foundation/image/color.h]: Mark inline?

File: src/appleseed/renderer/modeling/frame/frame.cpp [hunk 3]
```diff
@@ -571,20 +571,23 @@ namespace
     void transform_to_srgb(Tile& tile)
     {
         assert(tile.get_channel_count() == 4);
+        assert(tile.get_pixel_format() == PixelFormatHalf);
 
-        Color4f* pixel_ptr = reinterpret_cast<Color4f*>(tile.pixel(0));
-        Color4f* pixel_end = pixel_ptr + tile.get_pixel_count();
+        using Color4h = Color<half, 4>;
+
+        Color4h* pixel_ptr = reinterpret_cast<Color<half,4>*>(tile.pixel(0));
```
Comment (dictoon) [inline src/appleseed/renderer/modeling/frame/frame.cpp]: Space after comma: `Color<half, 4>`
