### PR TITLE
BCD multiscale denoiser fix

### LINKED ISSUE #2136: Fix denoising artifacts
Size issue ?
And check why rendering the same thing doesn't yield the same result
f0fb2c166550834bdbb72ced1ae14962ee77f1a6_1_500x500

### PR DESCRIPTION
**Pull request by est77**
fix #2136

### CODE REVIEW

File: src/thirdparty/bcd/bcd/MultiscaleDenoiser.cpp [hunk 1]
```diff
@@ -535,9 +540,9 @@ void MultiscaleDenoiser::downscale(
         for (col = 0; col < downscaledWidth; ++col)
         {
             p1 = PixelPosition(2 * line, 2 * col);
-            p2 = p1 + PixelVector(1, 0);
-            p3 = p1 + PixelVector(0, 1);
-            p4 = p1 + PixelVector(1, 1);
+            p2 = i_rImage.clamp(p1 + PixelVector(1,0));
```
Comment (dictoon) [inline src/thirdparty/bcd/bcd/MultiscaleDenoiser.cpp]: Put back spaces before commas.

**Comment by dictoon** [comment]
Should be propose the changes to upstream, or did you actually got them from upstream?
